### PR TITLE
Add Travis CI test

### PR DESCRIPTION
**Pull request by sakama**
I added .travis.yml for Travis CI.
@muga Could you enable it?

I'll fix if CI fails.

### CODE REVIEW

**Comment by sakama** [comment]
@muga ping
I'll adjust before send another PR.

**Comment by muga** [comment]
@sakama Thank you for pinging me. Enabled.

**Comment by sakama** [comment]
Thanks. I'll check.

**Comment by sakama** [comment]
I think this configuration works fine.
https://travis-ci.org/muga/embulk-output-elasticsearch/builds

**Pull request merged**
