### PR TITLE
Create RetryHelper instance only at sendRequest() method

### PR DESCRIPTION
**Pull request by sakama**
This plugin sometimes hung up(processing stopped but doesn't finish with error).

To avoid this problem I changed implementation to create RetryHelper only at `ElasticsearchHttpClient.sendRequest()` and close RetryHelper every time.

### CODE REVIEW

**Comment by sakama** [comment]
Problem is still existing.
I may overlooked something.

**Comment by sakama** [comment]
I found job hang always happens when I don't specify following config.
Probably embulk-base-resetclient doesn't works properly when output task > 1.
```yaml
exec:
  min_output_tasks: 1
```

Anyway, it's better to apply this PR. 
Create Jetty92RetryHelper is not so heavy. Code will become simple and decrease resource unrelease problem.

**Comment by muga** [comment]
Thank you for fixing.

> I found job hang always happens when I don't specify following config.
> Probably embulk-base-resetclient doesn't works properly when output task > 1.

Can you investigate this issue before merging this PR into master? I think that we need to know the severity and the extent of the impact by this issue.

**Comment by sakama** [comment]
@muga Thanks. Yeah, it's better to check embulk-base-restclient or Embulk more.
But this fix should better than current version.

Current version also has execution job hang problem and code should become simple and decrease resource unrelease problem.

**Review by muga — APPROVED** [review]
Understand. LGTM. When you have time, please file another ticket to investigate this issue.

**Pull request merged**
